# Generated by Django 5.0.3 on 2024-03-14 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='filmPerson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(blank=True, choices=[('producer', 'Produser'), ('actor', 'Actor'), ('director', 'Director'), ('screenwriteer', 'Screenwriter'), ('composer', 'Composer')], max_length=255, null=True)),
                ('name', models.CharField(max_length=255)),
                ('photo', models.ImageField(upload_to='films/images/person/')),
                ('biography', models.TextField()),
                ('birthday', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Film',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('poster', models.ImageField(upload_to='films/images/posters/')),
                ('producer', models.ManyToManyField(related_name='produced_films', to='films.filmperson')),
            ],
        ),
    ]
