# Generated by Django 5.0.3 on 2024-03-14 16:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('description', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='film',
            name='actor',
            field=models.ManyToManyField(related_name='acted_in_films', to='films.filmperson'),
        ),
        migrations.AddField(
            model_name='film',
            name='age',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='film',
            name='budget',
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='film',
            name='composer',
            field=models.ManyToManyField(related_name='composed_films', to='films.filmperson'),
        ),
        migrations.AddField(
            model_name='film',
            name='country',
            field=models.CharField(default='USA', max_length=100),
        ),
        migrations.AddField(
            model_name='film',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='film',
            name='director',
            field=models.ManyToManyField(related_name='directed_films', to='films.filmperson'),
        ),
        migrations.AddField(
            model_name='film',
            name='duration',
            field=models.SmallIntegerField(default=23),
        ),
        migrations.AddField(
            model_name='film',
            name='screenwriter',
            field=models.ManyToManyField(related_name='writed_films', to='films.filmperson'),
        ),
        migrations.AddField(
            model_name='film',
            name='trailer',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='film',
            name='year',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='FilmReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('likes', models.PositiveIntegerField(default=0)),
                ('dislikes', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviews', to=settings.AUTH_USER_MODEL)),
                ('film', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='films.film')),
            ],
        ),
        migrations.AddField(
            model_name='film',
            name='genres',
            field=models.ManyToManyField(related_name='films', to='films.genre'),
        ),
    ]
